config/routes.rb
Rails.application.routes.draw do
  resources :mates

  root 'mates#index'

end

app/models/mate.rb
class Mate < ActiveRecord::Base

	def calculate
		if operacao == "Plus"
			self.gama = self.alfa + self.beta

		else
			if operacao == "Minus"
				self.gama = self.alfa - self.beta
			else
				if operacao == "Multi"
					self.gama = self.alfa * self.beta
				else
					if operacao == "Divi"
							self.gama = self.alfa / self.beta
					end
				end
			end	
		end


		return self
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mates_controller.rb
class MatesController < ApplicationController
  before_action :set_mate, only: [:show, :edit, :update, :destroy]

  # GET /mates
  # GET /mates.json
  def index
    @mates = Mate.all
  end

  # GET /mates/1
  # GET /mates/1.json
  def show
  end

  # GET /mates/new
  def new
    @mate = Mate.new
    @mate.alfa = 12
    @mate.beta = 35

  end

  # GET /mates/1/edit
  def edit
  end

  # POST /mates
  # POST /mates.json
  def create
    @mate = Mate.new(mate_params).calculate

    respond_to do |format|
      if @mate.save
        format.html { redirect_to @mate, notice: 'Mate was successfully created.' }
        format.json { render :show, status: :created, location: @mate }
      else
        format.html { render :new }
        format.json { render json: @mate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mates/1
  # PATCH/PUT /mates/1.json
  def update
    respond_to do |format|
      if @mate.update(mate_params)
        format.html { redirect_to @mate, notice: 'Mate was successfully updated.' }
        format.json { render :show, status: :ok, location: @mate }
      else
        format.html { render :edit }
        format.json { render json: @mate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mates/1
  # DELETE /mates/1.json
  def destroy
    @mate.destroy
    respond_to do |format|
      format.html { redirect_to mates_url, notice: 'Mate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mate
      @mate = Mate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mate_params
      params.require(:mate).permit(:alfa, :beta, :gama, :operacao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mates_helper.rb
module MatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculadora</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mates/_form.html.erb
<%= form_for(@mate) do |f| %>
  <% if @mate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mate.errors.count, "error") %> prohibited this mate from being saved:</h2>

      <ul>
      <% @mate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2> Como uma RPN </h2>

  <div class="field">
    <%= f.label :alfa %><br>
    <%= f.text_field :alfa %>
  </div>
  <div class="field">
    <%= f.label :beta %><br>
    <%= f.text_field :beta %>
  </div>
  <div class="field">
   
    <%= f.select :operacao , [["Plus", "Plus"], ["Minus", "Minus"], ["Divi", "Divi"] ,["Multi", "Multi"]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mates/edit.html.erb
<h1>Editing Mate</h1>

<%= render 'form' %>

<%= link_to 'Show', @mate %> |
<%= link_to 'Back', mates_path %>

app/views/mates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mates</h1>

<table>
  <thead>
    <tr>
      <th>Alfa</th>
      <th>Beta</th>
      <th>Operation</th>
      <th>Gama</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mates.each do |mate| %>
      <tr>
        <td><%= mate.alfa %></td>
        <td><%= mate.beta %></td>
        <td><%= mate.operacao %></td>
        <td><%= mate.gama %></td>
        <td><%= link_to 'Show', mate %></td>
        <td><%= link_to 'Edit', edit_mate_path(mate) %></td>
        <td><%= link_to 'Destroy', mate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mate', new_mate_path %>

app/views/mates/new.html.erb
<h1>New Mate</h1>

<%= render 'form' %>

<%= link_to 'Back', mates_path %>

app/views/mates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alfa:</strong>
  <%= @mate.alfa %>
</p>

<p>
  <strong>Beta:</strong>
  <%= @mate.beta %>
</p>

<p>
  <strong>Gama:</strong>
  <%= @mate.gama %>
</p>

<%= link_to 'Edit', edit_mate_path(@mate) %> |
<%= link_to 'Back', mates_path %>